/*
 * This file is generated by jOOQ.
*/
package co.simplon.laposte.domain.tables;


import co.simplon.laposte.domain.Dbprojet;
import co.simplon.laposte.domain.Keys;
import co.simplon.laposte.domain.tables.records.UtilisateurRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Utilisateur extends TableImpl<UtilisateurRecord> {

    private static final long serialVersionUID = 2067919419;

    /**
     * The reference instance of <code>dbprojet.utilisateur</code>
     */
    public static final Utilisateur UTILISATEUR = new Utilisateur();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtilisateurRecord> getRecordType() {
        return UtilisateurRecord.class;
    }

    /**
     * The column <code>dbprojet.utilisateur.id</code>.
     */
    public final TableField<UtilisateurRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dbprojet.utilisateur.pseudo</code>.
     */
    public final TableField<UtilisateurRecord, String> PSEUDO = createField("pseudo", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>dbprojet.utilisateur.mot_de_passe</code>.
     */
    public final TableField<UtilisateurRecord, String> MOT_DE_PASSE = createField("mot_de_passe", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>dbprojet.utilisateur.email</code>.
     */
    public final TableField<UtilisateurRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>dbprojet.utilisateur.derniere_maj</code>.
     */
    public final TableField<UtilisateurRecord, Timestamp> DERNIERE_MAJ = createField("derniere_maj", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>dbprojet.utilisateur</code> table reference
     */
    public Utilisateur() {
        this("utilisateur", null);
    }

    /**
     * Create an aliased <code>dbprojet.utilisateur</code> table reference
     */
    public Utilisateur(String alias) {
        this(alias, UTILISATEUR);
    }

    private Utilisateur(String alias, Table<UtilisateurRecord> aliased) {
        this(alias, aliased, null);
    }

    private Utilisateur(String alias, Table<UtilisateurRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbprojet.DBPROJET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UtilisateurRecord, Integer> getIdentity() {
        return Keys.IDENTITY_UTILISATEUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UtilisateurRecord> getPrimaryKey() {
        return Keys.KEY_UTILISATEUR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UtilisateurRecord>> getKeys() {
        return Arrays.<UniqueKey<UtilisateurRecord>>asList(Keys.KEY_UTILISATEUR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Utilisateur as(String alias) {
        return new Utilisateur(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Utilisateur rename(String name) {
        return new Utilisateur(name, null);
    }
}
