-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 19:25:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbprojet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbprojet` ;

-- -----------------------------------------------------
-- Schema dbprojet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbprojet` DEFAULT CHARACTER SET utf8 ;
USE `dbprojet` ;

-- -----------------------------------------------------
-- Table `dbprojet`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojet`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `dbprojet`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `derniere_maj` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbprojet`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojet`.`role` ;

CREATE TABLE IF NOT EXISTS `dbprojet`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `derniere_maj` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojet`.`utilisateur_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojet`.`utilisateur_role` ;

CREATE TABLE IF NOT EXISTS `dbprojet`.`utilisateur_role` (
  `utilisateur_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `role_id`),
  INDEX `fk_utilisateur_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_utilisateur_has_role_utilisateur_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_utilisateur_has_role_utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `dbprojet`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `dbprojet`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
