/*
 * This file is generated by jOOQ.
*/
package co.simplon.laposte.domain.tables.records;


import co.simplon.laposte.domain.tables.Utilisateur;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UtilisateurRecord extends UpdatableRecordImpl<UtilisateurRecord> implements Record5<Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = -388144187;

    /**
     * Setter for <code>dbprojet.utilisateur.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dbprojet.utilisateur.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dbprojet.utilisateur.pseudo</code>.
     */
    public void setPseudo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dbprojet.utilisateur.pseudo</code>.
     */
    public String getPseudo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dbprojet.utilisateur.mot_de_passe</code>.
     */
    public void setMotDePasse(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dbprojet.utilisateur.mot_de_passe</code>.
     */
    public String getMotDePasse() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dbprojet.utilisateur.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dbprojet.utilisateur.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dbprojet.utilisateur.derniere_maj</code>.
     */
    public void setDerniereMaj(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dbprojet.utilisateur.derniere_maj</code>.
     */
    public Timestamp getDerniereMaj() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Utilisateur.UTILISATEUR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Utilisateur.UTILISATEUR.PSEUDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Utilisateur.UTILISATEUR.MOT_DE_PASSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Utilisateur.UTILISATEUR.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Utilisateur.UTILISATEUR.DERNIERE_MAJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMotDePasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDerniereMaj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord value2(String value) {
        setPseudo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord value3(String value) {
        setMotDePasse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord value5(Timestamp value) {
        setDerniereMaj(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UtilisateurRecord
     */
    public UtilisateurRecord() {
        super(Utilisateur.UTILISATEUR);
    }

    /**
     * Create a detached, initialised UtilisateurRecord
     */
    public UtilisateurRecord(Integer id, String pseudo, String motDePasse, String email, Timestamp derniereMaj) {
        super(Utilisateur.UTILISATEUR);

        set(0, id);
        set(1, pseudo);
        set(2, motDePasse);
        set(3, email);
        set(4, derniereMaj);
    }
}
