/*
 * This file is generated by jOOQ.
*/
package co.simplon.laposte.domain.tables.records;


import co.simplon.laposte.domain.tables.UtilisateurRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UtilisateurRoleRecord extends UpdatableRecordImpl<UtilisateurRoleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1264449481;

    /**
     * Setter for <code>jooqdatabase.utilisateur_role.utilisateur_id</code>.
     */
    public void setUtilisateurId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooqdatabase.utilisateur_role.utilisateur_id</code>.
     */
    public Integer getUtilisateurId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooqdatabase.utilisateur_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooqdatabase.utilisateur_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UtilisateurRole.UTILISATEUR_ROLE.UTILISATEUR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UtilisateurRole.UTILISATEUR_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUtilisateurId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRoleRecord value1(Integer value) {
        setUtilisateurId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRoleRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilisateurRoleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UtilisateurRoleRecord
     */
    public UtilisateurRoleRecord() {
        super(UtilisateurRole.UTILISATEUR_ROLE);
    }

    /**
     * Create a detached, initialised UtilisateurRoleRecord
     */
    public UtilisateurRoleRecord(Integer utilisateurId, Integer roleId) {
        super(UtilisateurRole.UTILISATEUR_ROLE);

        set(0, utilisateurId);
        set(1, roleId);
    }
}
